//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class IGOrder
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public IGOrder()
        {
            this.IGOrderlist = new HashSet<IGOrderlist>();
            this.IGVMLog = new HashSet<IGVMLog>();
        }
    
        public bool Istest { get; set; }
        public System.Guid IGOrderid { get; set; }
        public string IGOrdernumber { get; set; }
        public Nullable<System.Guid> Productid { get; set; }
        public Nullable<System.Guid> Categoryid { get; set; }
        public Nullable<System.Guid> IGMemberid { get; set; }
        public string Url { get; set; }
        public string Service { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<int> Remains { get; set; }
        public int IGOrderStatus { get; set; }
        public Nullable<System.DateTime> Duedate { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    
        public virtual CategoryMessage CategoryMessage { get; set; }
        public virtual IGMembers IGMembers { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IGOrderlist> IGOrderlist { get; set; }
        public virtual Product Product { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IGVMLog> IGVMLog { get; set; }
    }
}
