//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudControl.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class CloudControlEntities : DbContext
    {
        public CloudControlEntities()
            : base("name=CloudControlEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AdminLims> AdminLims { get; set; }
        public virtual DbSet<Admins> Admins { get; set; }
        public virtual DbSet<Lims> Lims { get; set; }
        public virtual DbSet<Message> Message { get; set; }
        public virtual DbSet<Setting> Setting { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
        public virtual DbSet<Useragent> Useragent { get; set; }
        public virtual DbSet<CategoryProduct> CategoryProduct { get; set; }
        public virtual DbSet<CategoryMessage> CategoryMessage { get; set; }
        public virtual DbSet<FBOrderlist> FBOrderlist { get; set; }
        public virtual DbSet<IGOrderlist> IGOrderlist { get; set; }
        public virtual DbSet<YTOrderlist> YTOrderlist { get; set; }
        public virtual DbSet<IGMembersLoginlog> IGMembersLoginlog { get; set; }
        public virtual DbSet<YTMembersLoginlog> YTMembersLoginlog { get; set; }
        public virtual DbSet<IGMembers> IGMembers { get; set; }
        public virtual DbSet<YTMembers> YTMembers { get; set; }
        public virtual DbSet<FBMembers> FBMembers { get; set; }
        public virtual DbSet<FBMembersLoginlog> FBMembersLoginlog { get; set; }
        public virtual DbSet<IGOrder> IGOrder { get; set; }
        public virtual DbSet<YTOrder> YTOrder { get; set; }
        public virtual DbSet<FBVMLog> FBVMLog { get; set; }
        public virtual DbSet<IGVMLog> IGVMLog { get; set; }
        public virtual DbSet<YTVMLog> YTVMLog { get; set; }
        public virtual DbSet<FBOrder> FBOrder { get; set; }
        public virtual DbSet<FBVMStatus> FBVMStatus { get; set; }
        public virtual DbSet<IGVMStatus> IGVMStatus { get; set; }
        public virtual DbSet<YTVMStatus> YTVMStatus { get; set; }
        public virtual DbSet<Product> Product { get; set; }
    }
}
