//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YTMembers
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public YTMembers()
        {
            this.YTMembersLoginlog = new HashSet<YTMembersLoginlog>();
            this.YTOrderlist = new HashSet<YTOrderlist>();
            this.YTOrder = new HashSet<YTOrder>();
        }
    
        public int Isenable { get; set; }
        public int Isdocker { get; set; }
        public System.Guid YTMemberid { get; set; }
        public Nullable<System.Guid> Productid { get; set; }
        public string YT_Account { get; set; }
        public string YT_Password { get; set; }
        public string YT_Name { get; set; }
        public string Useragent { get; set; }
        public string Youtubelink { get; set; }
        public string Cookie { get; set; }
        public Nullable<long> Lastdate { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YTMembersLoginlog> YTMembersLoginlog { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YTOrderlist> YTOrderlist { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<YTOrder> YTOrder { get; set; }
        public virtual Product Product { get; set; }
    }
}
