//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace CloudControl.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class YTOrderlist
    {
        public Nullable<System.Guid> YTOrderid { get; set; }
        public System.Guid YTOrderlistid { get; set; }
        public Nullable<System.Guid> YTMemberid { get; set; }
        public Nullable<System.Guid> Productid { get; set; }
        public string YTAccount { get; set; }
        public Nullable<System.DateTime> Updatedate { get; set; }
        public Nullable<System.DateTime> Createdate { get; set; }
    
        public virtual YTMembers YTMembers { get; set; }
        public virtual YTOrder YTOrder { get; set; }
    }
}
